#!/bin/sh
# Resolve HERMES_GATEWAY / HERMES_URL into an nginx upstream.
# Usage:
#   hermes-gateway.sh write [dest]
#   hermes-gateway.sh print <value>
set -eu

DEFAULT_SERVER='host.docker.internal:8642'
DEFAULT_DEST='/tmp/hermes-gateway.conf'

usage() {
  printf '%s\n' "Usage: hermes-gateway.sh write [dest] | print <value>" >&2
  exit 2
}

is_number() {
  case ${1:-} in
    ''|*[!0-9]*) return 1 ;;
  esac
  return 0
}

is_port() {
  is_number "${1:-}" || return 1
  [ "$1" -ge 1 ] && [ "$1" -le 65535 ]
}

is_octet() {
  is_number "${1:-}" || return 1
  [ "$1" -le 255 ]
}

is_hostname() {
  case ${1:-} in
    ''|.*|*.) return 1 ;;
    *[!A-Za-z0-9._-]*) return 1 ;;
  esac
  return 0
}

is_ipv4() {
  case ${1:-} in
    ''|*[!0-9.]*) return 1 ;;
  esac
  old_ifs=$IFS
  IFS=.
  # shellcheck disable=SC2086
  set -- $1
  IFS=$old_ifs
  [ $# -eq 4 ] || return 1
  for octet in "$1" "$2" "$3" "$4"; do
    is_octet "$octet" || return 1
  done
  return 0
}

is_ipv6_literal() {
  case ${1:-} in
    \[*:*\]) ;;
    *) return 1 ;;
  esac
  inner=${1#\[}
  inner=${inner%\]}
  case $inner in
    ''|*[[\]]*) return 1 ;;
    *[!0-9A-Fa-f:]*) return 1 ;;
  esac
  return 0
}

fail_parse() {
  printf '%s\n' "$1" >&2
  exit 1
}

# Prints "host port" on success. Host is hostname, IPv4, or [IPv6].
parse_hermes_gateway() {
  raw=${1:-}
  raw=$(printf '%s' "$raw" | tr -d '\r\n\t ')
  [ -n "$raw" ] || raw=$DEFAULT_SERVER

  case $raw in
    *[';{}"'\\'$']*|*'`'*|*'|'*)
      fail_parse 'HERMES_GATEWAY contains characters that cannot be used in the nginx upstream.'
      ;;
    https://*)
      fail_parse 'HERMES_GATEWAY must be HTTP host:port. TLS terminates at your tunnel; the container talks to Hermes over HTTP.'
      ;;
    http://*) raw=${raw#http://} ;;
  esac

  case $raw in
    *@*|*/*|*'?'*|*#*)
      fail_parse 'HERMES_GATEWAY cannot include credentials, a path, or a query.'
      ;;
  esac

  host=''
  port=''
  case $raw in
    \[*)
      host="${raw%%]*}]"
      rest=${raw#*]}
      is_ipv6_literal "$host" || fail_parse 'HERMES_GATEWAY IPv6 address must be written as [address]:port.'
      case $rest in
        '') port=8642 ;;
        :*) port=${rest#:} ;;
        *) fail_parse 'HERMES_GATEWAY IPv6 address must be written as [address]:port.' ;;
      esac
      ;;
    *:*)
      host=${raw%:*}
      port=${raw##*:}
      if [ "$host" = "$raw" ] || [ "$port" = "$raw" ]; then
        fail_parse 'HERMES_GATEWAY must look like host:port.'
      fi
      ;;
    *)
      host=$raw
      port=8642
      ;;
  esac

  is_port "$port" || fail_parse 'HERMES_GATEWAY port must be a number from 1 to 65535.'
  if is_ipv6_literal "$host"; then
    :
  elif is_ipv4 "$host"; then
    :
  elif is_hostname "$host"; then
    :
  else
    fail_parse 'HERMES_GATEWAY host must be a hostname, IPv4 address, or [IPv6] address.'
  fi

  printf '%s %s\n' "$host" "$port"
}

write_upstream() {
  dest=${1:-$DEFAULT_DEST}
  host=$2
  port=$3
  umask 022
  cat > "$dest" <<EOF
# Generated from HERMES_GATEWAY. Do not edit this file.
upstream hermes_gateway {
    server ${host}:${port};
    keepalive 16;
}
EOF
}

cmd=${1:-}
case $cmd in
  write)
    dest=${2:-$DEFAULT_DEST}
    value=${HERMES_GATEWAY:-${HERMES_URL:-$DEFAULT_SERVER}}
    parsed=$(parse_hermes_gateway "$value")
    host=${parsed% *}
    port=${parsed#* }
    write_upstream "$dest" "$host" "$port"
    printf 'Hermes PWA proxy upstream: %s:%s\n' "$host" "$port"
    ;;
  print)
    [ $# -eq 2 ] || usage
    parse_hermes_gateway "$2"
    ;;
  *)
    usage
    ;;
esac
